### PR TITLE
OnceCell for Jwks fetching

### PR DESCRIPTION
**Pull request by x04**
Also fixed `default_features` deprecation warning on chrono dep.

### CODE REVIEW

**Comment by logan-stytch** [comment]
Hey @x04, thanks for the contribution, but we've intentionally chosen to *not* use `tokio` in this project since it locks anyone who might use the project into the same async runtime. The current code is agnostic of the underlying async backend being used, which means it's compatible with tokio, async-std, and any other runtime people may choose to use.

The current solution should be sufficient and work with any runtime, but if you have a use case where it's not working well for you, we'd love to hear about it and brainstorm a way to make this better.

**Comment by x04** [comment]
@logan-stytch you use `reqwest` which "requires" `tokio`, unless you use the `tokio1` compatibility feature of `async-std`. Also I used `tokio` with only the `sync` feature enabled, which is entirely compatible `async-std` regardless of the `tokio1` feature, unlike the `reqwest` dependency. I have created an example to show this.

```rust
use tokio::sync::OnceCell;

static ONCE: OnceCell<u32> = OnceCell::const_new();

#[async_std::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // this will work regardless of `tokio1` feature
    let cell: OnceCell<i32> = OnceCell::new();
    let cell_value = cell.get_or_init(|| async { 1234 }).await;
    println!("{}", *cell_value);

    // comment this to not crash when `tokio1` feature is not enabled
    let resp = reqwest::get("https://httpbin.org/get").await?;
    assert!(resp.status().is_success());

    Ok(())
}
```

```
[package]
name = "reqwest-proof"
version = "0.1.0"
edition = "2021"

[dependencies]
async-std = { version = "1", features = ["tokio1", "attributes"] }
tokio = { version = "1", features = ["sync"], default-features = false }
reqwest = "0.12"
```

If you disable the `tokio1` feature on async-std this will crash on the httpbin fetch. However the OnceCell still works.

**Comment by logan-stytch** [comment]
@x04, interesting, and thanks for the example. I had thought that our usage of `reqwest` only needed `tokio` when using the `default-tls` feature, but perhaps that was incorrect. I apologize for the misunderstanding. Let me reopen this PR.

**Comment by logan-stytch** [comment]
@x04 - sorry for the delay in review here. If you wouldn't mind, could you bump the `version` in `Cargo.toml` to `6.2.0`? This PR looks good. We appreciate your contribution!

**Review by logan-stytch — APPROVED** [review]

**Pull request merged**
